setwd("/media/alf/datos/drive/CEU/DOCENCIA/materiales/estadistica/presentaciones/statistics_manual")
library(tikzDevice)
library(plyr)
library(plotly)
library(shape)
require(Hmisc)

# Color definition
color1<-rgb(5,161,230,max=255)
color2<-rgb(238,50,36,max=255)
color3<-"green3"
color4<-rgb(169,78,145,max=255)
color5<-rgb(238,50,36,alpha=100,max=255)


options(tikzDefaultEngine = "xetex")

# Density function 
tikz(file="img/continuous_random_variables/density_function.tex", width=5, height=4)
x<-seq(0,30,length=100) 
y2<-dchisq(x,df=10) 
par(mar=c(3.5,3.5,2,1), mgp=c(2.2,0.6,0))
plot(x, y2, xlim=c(0,30), ylim=c(0,0.11), type="n", xlab="$X$", ylab="Probability density $f(x)$", yaxs="i", axes=FALSE) 
axis(side=1, at=c(x[20],x[60]), labels=c("a","b"))
polygon(c(x[20],x[20:60],x[60]), c(0,y2[20:60],0), col=color5, lty=0) 
lines(x, y2, type="l", col=color1, lwd=2)
text(12,0.02,"$\\displaystyle \\int_a^b f(x)\\,dx$")
box()
dev.off()

# Continuous uniform U(0,1) density function
tikz(file="img/continuous_random_variables/uniform_density_function.tex", width=4, height=4)
par(mar=c(3.5,3.5,3,1), mgp=c(2.2,0.6,0), las=1)
x <- seq(0, 1, length=10)
y <- dunif(x, min=0, max=1)
plot(x, y, type="l", xlab="X", xlim=c(-0.1,1.1), ylim=c(0,1.2), ylab="Probability density $f(x)$", main="Continuous uniform distribution U(0,1)", yaxs="i", col=color1, lwd=2)
segments(0,0,0,1, lty=2, col="gray")
segments(1,0,1,1, lty=2, col="gray")
dev.off()

# Continuous uniform U(0,1) distribution function
tikz(file="img/continuous_random_variables/uniform_distribution_function.tex", width=4, height=4)
par(mar=c(3.5,3.5,3,1), mgp=c(2.2,0.6,0), las=1)
x <- seq(0, 1, length=10)
y <- punif(x, min=0, max=1)
plot(c(-0.2,x,1.2), c(0,y,1), type="l", xlab="X", xlim=c(-0.1,1.1), ylim=c(0,1.2), ylab="Cummulative probability $F(x)$", main="Continuous uniform distribution U(0,1)", yaxs="i", col=color1, lwd=2)
dev.off()

# Probability calculation uniform 
tikz(file="img/continuous_random_variables/uniform_probability_calculation.tex", width=4, height=4)
par(mar=c(3.5,3.5,3,1), mgp=c(2.2,0.6,0), las=1)
x <- seq(0, 15, by=5)
y <- dunif(x, min=0, max=15)
plot(x, y, type="n", ylim=c(0,0.08), xlab="X", ylab="Probability density $f(x)$", main="Continuous unniform distribution U(0,15)", yaxs="i")
polygon(c(x[2],x[2],x[3],x[3]), c(0,y[1],y[2],0), col=color5, lty=0)
lines(x, y, col=color1, lwd=2)
text(7.5,0.04,"$P(5<X<10)=$")
text(7.5,0.03,"$\\displaystyle \\int_5^{10} \\frac{1}{15}\\,dx$")
dev.off()

# Normal density function
tikz(file="img/continuous_random_variables/normal_density_function.tex", width=4, height=4)
par(mar=c(3.5,3.5,3,1), mgp=c(2.2,0.6,0), las=1)
x <- seq(-3.3, 3.3, by=0.05)
plot(x, dnorm(x, mean=0, sd=1), ylim=c(0,0.45), xlab="X", ylab="Probability density $f(x)$", main="Normal distribution $N(\\mu,\\sigma)$", type="l", col=color1, lwd=2, yaxs="i",axes=FALSE)
axis(side=1, at=c(0), labels=c("$\\mu$"))
box()
dev.off()

# Standard normal density function
tikz(file="img/continuous_random_variables/standard_normal_density_function.tex", width=4, height=4)
par(mar=c(3.5,3.5,3,1), mgp=c(2.2,0.6,0), las=1)
x <- seq(-3.3, 3.3, by=0.05)
plot(x, dnorm(x, mean=0, sd=1), ylim=c(0,0.45), xlab="X", ylab="Probability density $f(x)$", main="Standard Normal distribution $N(0,1)$", type="l", col=color1, lwd=2, yaxs="i")
dev.off()

# Normal distributions with different means
tikz(file="img/continuous_random_variables/normal_density_function_different_means.tex", width=4, height=4)
par(mar=c(3.5,3.5,3,1), mgp=c(2.2,0.6,0), las=1)
x <- seq(-3.3, 3.3, by=0.05)
plot(x, dnorm(x, mean=0, sd=1), xlim=c(-3.2,5.2), ylim=c(0,0.45), xlab="X", ylab="Probability density $f(x)$", main="Normal distributions\n different means and equal variances", type="l", col=color1, lwd=2, yaxs="i")
lines(x+2, dnorm(x, mean=0, sd=1), type="l", col=color2, lwd=2)
legend("topright", lty=1, col=c(color1,color2), legend=c("$N(0,1)$", "$N(2,1)$"), bty="n") 
dev.off()

# Normal distributions with different variances
tikz(file="img/continuous_random_variables/normal_density_function_different_variances.tex", width=4, height=4)
par(mar=c(3.5,3.5,3,1), mgp=c(2.2,0.6,0), las=1)
x = seq(-3.3, 3.3, by=0.05)
y = seq(-6.581, 6.581, length=100)
plot(x, dnorm(x, mean=0, sd=1), xlim=c(-6.5,6.5), ylim=c(0,0.45), xlab="X", ylab="Probability density $f(x)$", main="Normal distributions\n equal means and different variances", type="l", col=color1, lwd=2, yaxs="i")
lines(y, dnorm(y, mean=0, sd=2), type="l", col=color2, lwd=2)
legend("topright", lty=1, col=c(color1,color2), legend=c("$N(0,1)$", "$N(0,2)$"), bty="n") 
dev.off()

# Normal distribution function
tikz(file="img/continuous_random_variables/normal_distribution_function.tex", width=4, height=4)
par(mar=c(3.5,3.5,3,1), mgp=c(2.2,0.6,0), las=1)
x <- seq(-3.3, 3.3, by=0.05)
plot(x, pnorm(x, mean=0, sd=1), xlab="X", ylab="Cummulative probability $F(x)$", main="Normal distribution $N(\\mu,\\sigma)$", type="l", col=color1, lwd=2, yaxs="i",axes=FALSE)
axis(side=1, at=c(0), labels=c("$\\mu$"))
box()
dev.off()

# Normal distribution intevals
tikz(file="img/continuous_random_variables/normal_properties2.tex", width=4, height=4)
par(mar=c(3.5,3.5,3,1), mgp=c(2.2,0.6,0), las=1)
x <- seq(-3.3, 3.3, by=0.05)
y <- dnorm(x, mean=0, sd=1)
x1 <- seq(-1, 1, by=0.05)
y1 <- dnorm(x1, mean=0, sd=1)
x2 <- seq(-2, 2, by=0.05)
y2 <- dnorm(x2, mean=0, sd=1)
x3 <- seq(-3, 3, by=0.05)
y3 <- dnorm(x3, mean=0, sd=1)
plot(x, y, ylim=c(0,0.45), xlab="X", ylab="Probability density $f(x)$", main="Normal distribution $N(\\mu,\\sigma)$", type="n", col=color1, lwd=2, yaxs="i",axes=FALSE)
axis(side=1, at=c(0), labels=c("$\\mu$"))
axis(side=1, at=c(-1,1), labels=c("$\\mu-\\sigma$","$\\mu+\\sigma$"))
polygon(c(x1[1],x1,x1[40]), c(0,y1,0), col=color5, lty=0)
text(0,0.15,"$68\\%$")
axis(side=1, at=c(-2,2), labels=c("$\\mu-2\\sigma$", "$\\mu+2\\sigma$"))
polygon(c(x2[1],x2,x2[80]), c(0,y2,0), col=color5, lty=0)
text(0,0.15,"$95\\%$")
axis(side=1, at=c(-3,3), labels=c("$\\mu-3\\sigma$","$\\mu+3\\sigma$"))
polygon(c(x3[1],x3,x3[120]), c(0,y3,0), col=color5, lty=0)
text(0,0.15,"$99\\%$")
lines(x, y, col=color1, lwd=2)
box()
dev.off()

# Normal distribution interval 68%
tikz(file="img/continuous_random_variables/normal_interval_68.tex", width=4, height=4)
par(mar=c(3.5,3.5,3,1), mgp=c(2.2,0.6,0), las=1)
x <- seq(-3.3, 3.3, by=0.05)
y <- dnorm(x, mean=0, sd=1)
x1 <- seq(-1, 1, by=0.05)
y1 <- dnorm(x1, mean=0, sd=1)
plot(x, y, ylim=c(0,0.45), xlab="X", ylab="Probability density $f(x)$", main="Normal distribution $N(\\mu,\\sigma)$", type="n", col=color1, lwd=2, yaxs="i",axes=FALSE)
axis(side=1, at=c(0), labels=c("$\\mu$"))
axis(side=1, at=c(-1,1), labels=c("$\\mu-\\sigma$","$\\mu+\\sigma$"))
polygon(c(x1[1],x1,x1[40]), c(0,y1,0), col=color5, lty=0)
text(0,0.15,"$68\\%$")
lines(x, y, col=color1, lwd=2)
box()
dev.off()

# Normal distribution interval 95%
tikz(file="img/continuous_random_variables/normal_interval_68.tex", width=4, height=4)
par(mar=c(3.5,3.5,3,1), mgp=c(2.2,0.6,0), las=1)
x <- seq(-3.3, 3.3, by=0.05)
y <- dnorm(x, mean=0, sd=1)
x2 <- seq(-2, 2, by=0.05)
y2 <- dnorm(x2, mean=0, sd=1)
plot(x, y, ylim=c(0,0.45), xlab="X", ylab="Probability density $f(x)$", main="Normal distribution $N(\\mu,\\sigma)$", type="n", col=color1, lwd=2, yaxs="i",axes=FALSE)
axis(side=1, at=c(0), labels=c("$\\mu$"))
axis(side=1, at=c(-2,2), labels=c("$\\mu-2\\sigma$", "$\\mu+2\\sigma$"))
polygon(c(x2[1],x2,x2[80]), c(0,y2,0), col=color5, lty=0)
text(0,0.15,"$95\\%$")
lines(x, y, col=color1, lwd=2)
box()
dev.off()

# Normal distribution interval 99%
tikz(file="img/continuous_random_variables/normal_interval_68.tex", width=4, height=4)
par(mar=c(3.5,3.5,3,1), mgp=c(2.2,0.6,0), las=1)
x <- seq(-3.3, 3.3, by=0.05)
y <- dnorm(x, mean=0, sd=1)
x3 <- seq(-3, 3, by=0.05)
y3 <- dnorm(x3, mean=0, sd=1)
plot(x, y, ylim=c(0,0.45), xlab="X", ylab="Probability density $f(x)$", main="Normal distribution $N(\\mu,\\sigma)$", type="n", col=color1, lwd=2, yaxs="i",axes=FALSE)
axis(side=1, at=c(0), labels=c("$\\mu$"))
axis(side=1, at=c(-3,3), labels=c("$\\mu-3\\sigma$","$\\mu+3\\sigma$"))
polygon(c(x3[1],x3,x3[120]), c(0,y3,0), col=color5, lty=0)
text(0,0.15,"$99\\%$")
lines(x, y, col=color1, lwd=2)
box()
dev.off()

# Computing probabilities with the standard normal distribution (left-tail)
tikz(file="img/continuous_random_variables/normal_probability_calculation_left_tail.tex", width=4, height=4)
par(mar=c(3.5,3.5,3,1), mgp=c(2.2,0.6,0), las=1)
x = seq(-3.32, 3.32, by=0.04)
y = dnorm(x,mean=0,sd=1)
x0 = x[97]
p0 = floor(pnorm(x0, mean=0, sd=1, lower.tail=TRUE)*10000)/10000
plot(x, y, ylim=c(0,0.45), xlab="X", ylab="Probability density $f(x)$", main="Standard normal distribution $N(0,1)$", type="n", yaxs="i",axes=FALSE)
axis(side=1, at=x0)
polygon(c(x[1],x[1:97],x[97]), c(0,y[1:97],0), col=color5, lty=0)
lines (x, y, type="l", col=color1, lwd=2)
text(-0.7,0.06,paste("F(",x0,")=",p0))
box()
dev.off()

# Standard normal distribution function
tikz(file="img/continuous_random_variables/standard_normal_distribution_function.tex", width=4, height=4)
par(mar=c(3.5,3.5,3,1), mgp=c(2.2,0.6,0), las=1)
x = seq(-3.32, 3.32, by=0.04)
y = dnorm(x,mean=0,sd=1)
x0 = x[97]
p0 = floor(pnorm(x0, mean=0, sd=1, lower.tail=TRUE)*10000)/10000
plot(x, y, ylim=c(0,0.45), xlab="$Z$", ylab="Probability density $f(z)$", main="Standard normal distribution $N(0,1)$", type="n", yaxs="i")
axis(side=1, at=x0, labels="$z_0$")
polygon(c(x[1],x[1:97],x[97]), c(0,y[1:97],0), col=color5, lty=0)
lines (x, y, type="l", col=color1, lwd=2)
text(-0.7,0.06,"$F(z_0)=P(Z\\leq z_0)$")
box()
dev.off()

# Computing probabilities with the normal distribution (right-tail)
tikz(file="img/continuous_random_variables/normal_probability_calculation_right_tail.tex", width=4, height=4)
par(mar=c(3.5,3.5,3,1), mgp=c(2.2,0.6,0), las=1)
x = seq(-3.32, 3.32, by=0.04)
y = dnorm(x,mean=0,sd=1)
x0 = x[97]
p0 = floor(pnorm(x0, mean=0, sd=1, lower.tail=TRUE)*10000)/10000
plot(x, y, ylim=c(0,0.45), xlab="X", ylab="Probability density $f(x)$", main="Standard normal distribution $N(0,1)$", type="n", yaxs="i",axes=FALSE)
axis(side=1, at=x0)
polygon(c(x[97],x[97:length(x)],x[length(x)]), c(0,y[97:length(x)],0), col=color5, lty=0)
lines (x, y, type="l", col=color1, lwd=2)
text(-0.7,0.06,paste("F(",x0,")=",p0))
text(1.2,0.06,paste("1-F(",x0,")"))
text(1.2,0.04,"=0.3015")
box()
dev.off()

# Chi-square density function
tikz(file="img/continuous_random_variables/chi_square_density_function.tex", width=4, height=4)
par(mar=c(3.5,3.5,3,1), mgp=c(2.2,0.6,0), las=1)
x = seq(0, 50, by=0.05)
y1 = dchisq(x, df=3)
y2 = dchisq(x, df=10)
y3 = dchisq(x, df=30)
plot(x, y1, xlab="X", ylab="Probability density $f(x)$", main="Chi-square distribution", type="l", col=color1, lwd=2, yaxs="i")
lines(x, y2, type="l", col=color2, lwd=2)
lines(x, y3, type="l", col=color3, lwd=2)
legend("topright", lty=1, lwd=2, col=c(color1,color2,color3), legend=c("$\\chi^2(3)$","$\\chi^2(10)$","$\\chi^2(30)$"), bty="n") 
box()
dev.off()

# Student's t density function
tikz(file="img/continuous_random_variables/student_t_density_function.tex", width=4, height=4)
par(mar=c(3.5,3.5,3,1), mgp=c(2.2,0.6,0), las=1)
x = seq(-3.3, 3.3, by=0.05)
y1 = dt(x, df=3)
y2 = dt(x, df=10)
y3 = dt(x, df=30)
plot(x, dnorm(x, mean=0, sd=1), ylim=c(0,0.45), xlab="X", ylab="Probability density $f(x)$", main="Student's T distribution", type="l", col=gray(0.5), lty=2, lwd=2, yaxs="i")
lines(x, y1, type="l", col=color1, lwd=2)
lines(x, y2, type="l", col=color2, lwd=2)
lines(x, y3, type="l", col=color3, lwd=2)
legend("topright", lty=c(1,1,1,2), lwd=2, col=c(color1,color2,color3,gray(0.5)), legend=c("$T(3)$","$T(10)$","$T(30)$","N(0,1)"), bty="n") 
box()
dev.off()

# Fisher's F density function
tikz(file="img/continuous_random_variables/fisher_f_density_function.tex", width=4, height=4)
par(mar=c(3.5,3.5,3,1), mgp=c(2.2,0.6,0), las=1)
x = seq(0, 5, by=0.05)
y1 = df(x, df1=3, df2=3)
y2 = df(x, df1=20, df2=10)
y3 = df(x, df1=30, df2=30)
plot(x, y3, xlab="X", ylab="Probability density $f(x)$", main="Fisher's F distribution", type="l", col=color3, lwd=2, yaxs="i")
lines(x, y1, type="l", col=color1, lwd=2)
lines(x, y2, type="l", col=color2, lwd=2)
legend("topright", lty=1, lwd=2, col=c(color1,color2,color3), legend=c("$F(3,3)$","$F(20,10)$","$F(30,30)$"), bty="n") 
box()
dev.off()



