setwd("/media/datos/Dropbox/ceu/docencia/materiales/estadistica/presentaciones/curso_estadistica")
require(Hmisc)

Datos <- read.table("datos/datos hijos coches.csv", header=TRUE, sep="\t", na.strings="NA", dec=".", strip.white=TRUE)
#Diagrama de barras de frecuencias absolutas de hijos
x11()
barplot(0,type="n",xlim=c(0,6), ylim=c(0,14))
par(cex.lab=1.2)
abline(h= (0:12)*2 , col ="gray" , lty =3) 
barplot(table(Datos$hijos), add=TRUE, main="Diagrama de barras de frecuencias absolutas", xlab="Número de hijos", ylab=expression(paste("Frecuencia absoluta ", italic(n[i]))), col="coral")
dev.copy2eps(file="img/descriptiva/diagrama_barras_frecuencia_absoluta.eps", width=5, height=5, pointsize=10)
dev.off()

xfig(file="img/descriptiva/diagrama_barras_frecuencia_absoluta.fig", onefile=TRUE, width=5, height=5, pointsize=10)
barplot(0,type="n",xlim=c(0,6), ylim=c(0,14))
par(cex.lab=1.2)
abline(h= (0:12)*2 , col ="gray" , lty =3) 
barplot(table(Datos$hijos), add=TRUE, main="Diagrama de barras de frecuencias absolutas", xlab="Número de hijos", ylab=expression(paste("Frecuencia absoluta ", italic(n[i]))), col="coral")
dev.off()

#Polígono de frecuencias absolutas de hijos
x11()
par(cex.lab=1.2)
plot(table(Datos$hijos), type="l", col="royalblue", main="Polígono de frecuencias absolutas", xlab="Número de hijos", ylab=expression(paste("Frecuencia absoluta ", italic(n[i]))))
abline(h= (0:12)*2 , col ="gray" , lty =3)
dev.copy2eps(file="img/descriptiva/poligono_frecuencia_absoluta.eps", width=5, height=5, pointsize=10)
dev.off()

xfig(file="img/descriptiva/poligono_frecuencia_absoluta.fig", onefile=TRUE, width=5, height=5, pointsize=10)
par(cex.lab=1.2)
plot(table(Datos$hijos), type="l", col="royalblue", main="Polígono de frecuencias absolutas", xlab="Número de hijos", ylab=expression(paste("Frecuencia absoluta ", italic(n[i]))))
abline(h= (0:12)*2 , col ="gray" , lty =3) 
dev.off()

#Diagrama de barras de frecuencias absolutas acumuladas de hijos
x11()
t <- c(2,8,22,24,25)
b <- barplot(t, type="n")
par(cex.lab=1.2)
abline(h= (0:26)*2 , col ="gray" , lty =3) 
barplot(t, add=TRUE, names.arg=c("0","1","2","3","4"), main="Diagrama de barras de frecuencias absolutas acumuladas", xlab="Número de hijos", ylab=expression(paste("Frecuencia absoluta acumulada ", italic(N[i]))), col="coral")
dev.copy2eps(file="img/descriptiva/diagrama_barras_frecuencia_acumulada.eps", width=5, height=5, pointsize=10)
dev.off()

xfig(file="img/descriptiva/diagrama_barras_frecuencia_acumulada.fig", onefile=TRUE, width=5, height=5, pointsize=10)
t <- c(2,8,22,24,25)
b <- barplot(t, type="n")
par(cex.lab=1.2)
abline(h= (0:26)*2 , col ="gray" , lty =3) 
barplot(t, add=TRUE, names.arg=c("0","1","2","3","4"), main="Diagrama de barras de frecuencias absolutas acumuladas", xlab="Número de hijos", ylab=expression(paste("Frecuencia absoluta acumulada ", italic(N[i]))), col="coral")
dev.off()


#Polígono de frecuencias absolutas acumuladas de hijos
x11()
par(cex.lab=1.2)
plot(c(-1,0,0,1,1,2,2,3,3,4,4,5),c(0,0,2,2,8,8,22,22,24,24,25,25), axes=FALSE, xlim=c(-0.2,4.2), type="n", xlab="Número de hijos", ylab=expression(paste("Frecuencia absoluta acumulada ", italic(N[i]))))
axis(1)
axis(2)
abline(h= (0:12)*2 , col ="gray" , lty =3) 
lines(c(-1,0,0,1,1,2,2,3,3,4,4,5),c(0,0,2,2,8,8,22,22,24,24,25,25),col="royalblue", lwd=2)
dev.copy2eps(file="img/descriptiva/poligono_frecuencia_acumulada.eps", width=5, height=5, pointsize=10)
dev.off()

xfig(file="img/descriptiva/poligono_frecuencia_acumulada.fig", onefile=TRUE, width=5, height=5, pointsize=10)
par(cex.lab=1.2)
plot(c(-1,0,0,1,1,2,2,3,3,4,4,5),c(0,0,2,2,8,8,22,22,24,24,25,25), axes=FALSE, xlim=c(-0.2,4.2), type="n", xlab="Número de hijos", ylab=expression(paste("Frecuencia absoluta acumulada ", italic(N[i]))))
axis(1)
axis(2)
abline(h= (0:12)*2 , col ="gray" , lty =3) 
lines(c(-1,0,0,1,1,2,2,3,3,4,4,5),c(0,0,2,2,8,8,22,22,24,24,25,25),col="royalblue", lwd=2)
dev.off()


Datos <- read.table("datos/datos estaturas pesos sexo.csv", header=TRUE, sep="\t", na.strings="NA", dec=".", strip.white=TRUE)

#Histograma de frecuencias absolutas de estaturas
x11()
par(cex.lab=1.2)
hist(Datos$estatura, ylim=c(0,12), main="Histograma de frecuencias absolutas", xlab="Estatura", ylab=expression(paste("Frecuencia absoluta ", italic(n[i]))), col="coral")
dev.copy2eps(file="img/descriptiva/histograma_frecuencia_absoluta.eps", width=5, height=5, pointsize=10)
dev.off()

xfig(file="img/descriptiva/histograma_frecuencia_absoluta.fig", onefile=TRUE, width=5, height=5, pointsize=10)
par(cex.lab=1.2)
hist(Datos$estatura, ylim=c(0,12), main="Histograma de frecuencias absolutas", xlab="Estatura", ylab=expression(paste("Frecuencia absoluta ", italic(n[i]))), col="coral")
dev.off()

#Polígono de frecuencias absolutas de estaturas
x11()
par(cex.lab=1.2)
h <- hist(Datos$estatura, plot=FALSE) 
amplitud <- h$mids[2] - h$mids[1]
xx <- c( h$mids[1]-amplitud, h$mids, tail(h$mids,1)+amplitud ) 
yy <- c(0, h$counts, 0)
hist(Datos$estatura, xlim=range(xx), ylim=c(0,12), main="Polígono de frecuencias absolutas", xlab="Estatura", ylab=expression(paste("Frecuencia absoluta ", italic(n[i]))), col="coral")
lines(xx, yy, lwd=2, col = "royalblue") 
dev.copy2eps(file="img/descriptiva/poligono_frecuencia_absoluta_agrupado.eps", width=5, height=5, pointsize=10)
dev.off()

xfig(file="img/descriptiva/poligono_frecuencia_absoluta_agrupado.fig", onefile=TRUE, width=5, height=5, pointsize=10)
par(cex.lab=1.2)
h <- hist(Datos$estatura, plot=FALSE) 
amplitud <- h$mids[2] - h$mids[1]
xx <- c( h$mids[1]-amplitud, h$mids, tail(h$mids,1)+amplitud ) 
yy <- c(0, h$counts, 0)
hist(Datos$estatura, xlim=range(xx), ylim=c(0,12), main="Polígono de frecuencias absolutas", xlab="Estatura", ylab=expression(paste("Frecuencia absoluta ", italic(n[i]))), col="coral")
lines(xx, yy, lwd=2, col = "royalblue") 
dev.off()

#Histograma de frecuencias acumuladas de estaturas
x11()
par(cex.lab=1.2)
h <- hist(Datos$estatura, plot=FALSE)
h$counts <- cumsum(h$counts)
plot(h, main="Histograma de frecuencias absolutas acumuladas", xlab="Estatura", ylab=expression(paste("Frecuencia absoluta acumulada ", italic(N[i]))), col="coral")
dev.copy2eps(file="img/descriptiva/histograma_frecuencia_acumulada.eps", width=5, height=5, pointsize=10)
dev.off() 

xfig(file="img/descriptiva/histograma_frecuencia_acumulada.fig", onefile=TRUE, width=5, height=5, pointsize=10)
par(cex.lab=1.2)
h <- hist(Datos$estatura, plot=FALSE)
h$counts <- cumsum(h$counts)
plot(h, main="Histograma de frecuencias absolutas acumuladas", xlab="Estatura", ylab=expression(paste("Frecuencia absoluta acumulada ", italic(N[i]))), col="coral")
dev.off() 


#Polígono de frecuencias acumuladas de estaturas
x11()
par(cex.lab=1.2)
h <- hist(Datos$estatura, plot=FALSE) 
h$counts <- cumsum(h$counts)
yy <- c(0, h$counts)
plot(h, main="Polígono de frecuencias absolutas acumuladas", xlab="Estatura", ylab=expression(paste("Frecuencia absoluta acumulada ", italic(N[i]))), col="coral")
lines(h$breaks, yy, lwd=2, col = "royalblue") 
dev.copy2eps(file="img/descriptiva/poligono_frecuencia_acumulada_agrupado.eps", width=5, height=5, pointsize=10)
dev.off()

xfig(file="img/descriptiva/poligono_frecuencia_acumulada_agrupado.fig", onefile=TRUE, width=5, height=5, pointsize=10)
par(cex.lab=1.2)
h <- hist(Datos$estatura, plot=FALSE) 
h$counts <- cumsum(h$counts)
yy <- c(0, h$counts)
plot(h, main="Polígono de frecuencias absolutas acumuladas", xlab="Estatura", ylab=expression(paste("Frecuencia absoluta acumulada ", italic(N[i]))), col="coral")
lines(h$breaks, yy, lwd=2, col = "royalblue") 
dev.off()

#Histograma hombres y mujeres
x11()
options(digits=1)
par(cex.lab=1.2)
out <- histbackback(split(Datos$estatura, Datos$sexo), xlim=c(-10,10), main = 'Histograma de estaturas por sexo', xlab=c("Hombres", "Mujeres"), ylab="Estatura")
abline(v= (-8:8)*2 , col ="gray" , lty =3) 
barplot(-out$left, col="coral" , horiz=TRUE, space=0, add=TRUE, axes=FALSE) 
barplot(out$right, col="royalblue1", horiz=TRUE, space=0, add=TRUE, axes=FALSE) 
dev.copy2eps(file="img/descriptiva/histograma_estatura_sexo.eps", width=5, height=5, pointsize=10)
dev.off()

xfig(file="img/descriptiva/histograma_estatura_sexo.fig", onefile=TRUE, width=5, height=5, pointsize=10)
options(digits=1)
par(cex.lab=1.2)
out <- histbackback(split(Datos$estatura, Datos$sexo), xlim=c(-10,10), main = 'Histograma de estaturas por sexo', xlab=c("Hombres", "Mujeres"), ylab="Estatura")
abline(v= (-8:8)*2 , col ="gray" , lty =3) 
barplot(-out$left, col="coral" , horiz=TRUE, space=0, add=TRUE, axes=FALSE) 
barplot(out$right, col="royalblue1", horiz=TRUE, space=0, add=TRUE, axes=FALSE) 
dev.off()

#Diagramas de cajas de hombres y mujeres
x11()
options(digits=2)
par(cex.lab=1.2)
boxplot(estatura~sexo, main="Diagrama de caja y bigotes de estaturas por sexo", ylab="Estatura", xlab="Sexo", ylim=c(150,200), labels=c("hombre","mujer"), col=c("coral","royalblue1"), data=Datos)
dev.copy2eps(file="img/descriptiva/diagrama_cajas_estatura_sexo.eps", width=5, height=5, pointsize=10)
dev.off()

xfig(file="img/descriptiva/diagrama_cajas_estatura_sexo.fig", onefile=TRUE, width=5, height=5, pointsize=10)
options(digits=2)
par(cex.lab=1.2)
boxplot(estatura~sexo, main="Diagrama de caja y bigotes de estaturas por sexo", ylab="Estatura", xlab="Sexo", ylim=c(150,200), col=c("coral","royalblue1"), data=Datos)
dev.off()

#Diagrama de sectores
Datos <- read.table("datos/datos grupos sanguineos.csv", header=TRUE, sep="\t", na.strings="NA", dec=".", strip.white=TRUE)
x11()
par(cex.lab=1.2, mai=c(0,0,0.5,0))
pie(table(Datos$grupo.sanguineo.hijo), main="Distribución del grupo sanguíneo", labels=c("grupo 0 16%", "grupo A 47%", "grupo AB 10%", "grupo B 27%"), col=c("lightgreen","coral", "royalblue", "brown"))
dev.copy2eps(file="img/descriptiva/diagrama_sectores_grupo_sanguineo.eps", width=5, height=5, pointsize=10)
dev.off()

xfig(file="img/descriptiva/diagrama_sectores_grupo_sanguineo.fig", onefile=TRUE, width=5, height=5, pointsize=10)
par(cex.lab=1.2, mai=c(0,0,0.5,0))
pie(table(Datos$grupo.sanguineo.hijo), main="Distribución del grupo sanguíneo", labels=c("grupo 0 16%", "grupo A 47%", "grupo AB 10%", "grupo B 27%"), col=c("lightgreen","coral", "royalblue", "brown"))
dev.off()

#Diagrama de caja y bigotes pesos recien nacidos
Datos <- read.table("datos/peso_recien_nacidos.csv", header=TRUE, sep=" ", na.strings="NA", dec=".", strip.white=TRUE)
x11()
par(cex.lab=1.2)
boxplot(Datos$peso, horizontal=TRUE, col="coral", pch=16, main="Diagrama de caja y bigotes del peso de recien nacidos", xlab="Peso (Kg)")
text(2.9,0.75,expression(italic(C[1])))
text(3.1,0.75,expression(italic(C[2])))
text(3.4,0.75,expression(italic(C[3])))
text(2,1.06,"Dato\n atípico")
dev.copy2eps(file="img/descriptiva/diagrama_caja.eps", width=5, height=5, pointsize=10)
dev.off()

xfig(file="img/descriptiva/diagrama_caja.fig", onefile=TRUE, width=5, height=5, pointsize=10)
par(cex.lab=1.2)
boxplot(Datos$peso, horizontal=TRUE, col="coral", pch=16, main="Diagrama de caja y bigotes del peso de recien nacidos", xlab="Peso (Kg)")
text(2.9,0.75,expression(italic(C[1])))
text(3.1,0.75,expression(italic(C[2])))
text(3.4,0.75,expression(italic(C[3])))
text(2,1.06,"Dato\n atípico")
dev.off()

#Diagrama de caja y bigotes estaturas
Datos <- read.table("datos/datos hijos coches.csv", header=TRUE, sep="\t", na.strings="NA", dec=".", strip.white=TRUE)
x11()
par(cex.lab=1.2)
boxplot(Datos$hijos, horizontal=TRUE, col="coral", pch=16, main="Diagrama de caja y bigotes del número de hijos", xlab="Número de hijos")
text(1,0.75,expression(italic(C[1])))
text(2,0.75,expression(italic(C[3])))
text(4,1.06,"Dato\n atípico")
dev.copy2eps(file="img/descriptiva/diagrama_caja_hijos.eps", width=5, height=5, pointsize=10)
dev.off()

xfig(file="img/descriptiva/diagrama_caja_hijos.fig", onefile=TRUE, width=5, height=5, pointsize=10)
par(cex.lab=1.2)
boxplot(Datos$hijos, horizontal=TRUE, col="coral", pch=16, main="Diagrama de caja y bigotes del número de hijos", xlab="Número de hijos")
text(1,0.75,expression(italic(C[1])))
text(2,0.75,expression(italic(C[3])))
text(4,1.06,"Dato\n atípico")
dev.off()

# Histograma simétrico
x11()
x <- rnorm(1000000)
m <- mean(x)
layout(matrix(c(1,2),2,1),heights=c(3,1))
par(mai=c(0,1,0.5,0),cex.lab=1.2)
hist(x,xlim=c(-3.5,3.5), ylim=c(0,0.4), xaxt="n", prob=T, main=expression(paste("Distribución simétrica ", italic(g[1]),"=",0)), xlab ="", ylab="Frecuencia relativa", col="coral")
text(m,0,expression(bar(italic(x))))
par(mai=c(0,1,0,0))
boxplot(x,horizontal=TRUE,axes=FALSE, outline=FALSE, col="coral")
dev.copy2eps(file="img/descriptiva/distribucion_simetrica.eps", width=5, height=5, pointsize=10)
dev.off()

xfig(file="img/descriptiva/distribucion_simetrica.fig", onefile=TRUE, width=5, height=5, pointsize=10)
layout(matrix(c(1,2),2,1),heights=c(3,1))
par(mai=c(0,1,0.5,0),cex.lab=1.2)
hist(x,xlim=c(-3.5,3.5), ylim=c(0,0.4), xaxt="n", prob=T, main=expression(paste("Distribución simétrica ",italic(g[1]),"=",0)), xlab ="", ylab="Frecuencia relativa", col="coral")
text(m,0,expression(bar(italic(x))))
par(mai=c(0,1,0,0))
boxplot(x,horizontal=TRUE,axes=FALSE, outline=FALSE, col="coral")
dev.off()

#Histograma asimétrico izquierda
x11()
x <- rchisq(1000000,8)
m <- mean(x)
layout(matrix(c(1,2),2,1),heights=c(3,1))
par(mai=c(0,1,0.5,0),cex.lab=1.2)
hist(-x, xlim=c(-30,0), ylim=c(0,0.12), xaxt="n", prob=T, main=expression(paste("Distribución asimétrica a la izquierda ",italic(g[1]<0))), ylab="Frecuencia relativa", col="coral")
text(-m,0,expression(bar(italic(x))))
par(mai=c(0,1,0,0))
boxplot(-x, horizontal=TRUE, axes=FALSE, outline=FALSE, col="coral")
dev.copy2eps(file="img/descriptiva/distribucion_asimetrica_izquierda.eps", width=5, height=5, pointsize=10)
dev.off()

xfig(file="img/descriptiva/distribucion_asimetrica_izquierda.fig", onefile=TRUE, width=5, height=5, pointsize=10)
layout(matrix(c(1,2),2,1),heights=c(3,1))
par(mai=c(0,1,0.5,0),cex.lab=1.2)
hist(-x, xlim=c(-30,0), ylim=c(0,0.12), xaxt="n", prob=T, main=expression(paste("Distribución asimétrica a la izquierda ",italic(g[1]<0))), ylab="Frecuencia relativa", col="coral")
text(-m,0,expression(bar(italic(x))))
par(mai=c(0,1,0,0))
boxplot(-x, horizontal=TRUE, axes=FALSE, outline=FALSE, col="coral")
dev.off()


#Histograma asimétrico derecha
x11()
x <- rchisq(1000000,8)
m <- mean(x)
layout(matrix(c(1,2),2,1),heights=c(3,1))
par(mai=c(0,1,0.5,0),cex.lab=1.2)
hist(x, xlim=c(0,30), ylim=c(0,0.12), xaxt="n", prob=T, main=expression(paste("Distribución asimétrica a la derecha ",italic(g[1]>0))), ylab="Frecuencia relativa", col="coral")
text(m,0,expression(bar(italic(x))))
par(mai=c(0,1,0,0))
boxplot(x, horizontal=TRUE, axes=FALSE, outline=FALSE, col="coral")
dev.copy2eps(file="img/descriptiva/distribucion_asimetrica_derecha.eps", width=5, height=5, pointsize=10)
dev.off()

xfig(file="img/descriptiva/distribucion_asimetrica_derecha.fig", onefile=TRUE, width=5, height=5, pointsize=10)
layout(matrix(c(1,2),2,1),heights=c(3,1))
par(mai=c(0,1,0.5,0),cex.lab=1.2)
hist(x, xlim=c(0,30), ylim=c(0,0.12), xaxt="n", prob=T, main=expression(paste("Distribución asimétrica a la derecha ",italic(g[1]>0))), ylab="Frecuencia relativa", col="coral")
text(m,0,expression(bar(italic(x))))
par(mai=c(0,1,0,0))
boxplot(x, horizontal=TRUE, axes=FALSE, outline=FALSE, col="coral")
dev.off()


#Distribución mesocúrtica
x11()
par(cex.lab=1.2)
x <- rnorm(1000000)
hist(x,xlim=c(-3.5,3.5), ylim=c(0,0.4),prob=T, main=expression(paste("Distribución mesocúrtica ",italic(g[2]),"=",0)), xlab ="", ylab="Frecuencia relativa", col="coral", axes=F)
axis(2)
curve(dnorm, from=-3.5, to=3.5, add=TRUE, col="royalblue", lwd=2) 
dev.copy2eps(file="img/descriptiva/distribucion_mesocurtica.eps", width=5, height=5, pointsize=10)
dev.off()

xfig(file="img/descriptiva/distribucion_mesocurtica.fig", onefile=TRUE, width=5, height=5, pointsize=10)
par(cex.lab=1.2)
hist(x,xlim=c(-3.5,3.5), ylim=c(0,0.4),prob=T, main=expression(paste("Distribución mesocúrtica ",italic(g[2]),"=",0)), xlab ="", ylab="Frecuencia relativa", col="coral", axes=F)
axis(2)
curve(dnorm, from=-3.5, to=3.5, add=TRUE, col="royalblue", lwd=2) 
dev.off()

#Distribución Platicúrtica
x11()
par(cex.lab=1.2)
x1 <- runif(10000,-3,3)
x2 <- runif(1000,-2.5,2.5)
x3 <- runif(1000,-2,2)
x4 <- runif(1000,-1.5,1.5)
x5 <- runif(1000,-1,1)
x6 <- runif(500,-0.5,0.5)
x  <- c(x1,x2,x3,x4,x5,x6)
hist(x, prob=T, ylim=c(0,0.4),main=expression(paste("Distribución platicúrtica ",italic(g[2]<0))), xlab ="", ylab="Frecuencia relativa", col="coral", axes=F)
axis(2)
curve(dnorm, from=-3.5, to=3.5, add=TRUE, col="royalblue", lwd=2)
dev.copy2eps(file="img/descriptiva/distribucion_platicurtica.eps", width=5, height=5, pointsize=10)
dev.off()

xfig(file="img/descriptiva/distribucion_platicurtica.fig", onefile=TRUE, width=5, height=5, pointsize=10)
hist(x, prob=T, ylim=c(0,0.4),main=expression(paste("Distribución platicúrtica ",italic(g[2]<0))), xlab ="", ylab="Frecuencia relativa", col="coral", axes=F)
axis(2)
curve(dnorm, from=-3.5, to=3.5, add=TRUE, col="royalblue", lwd=2)
dev.off()


#Distribución Leptocúrtica
x11()
par(cex.lab=1.2)
x1 <- runif(1000,-3,3)
x2 <- runif(1000,-2.5,2.5)
x3 <- runif(1000,-2,2)
x4 <- runif(4000,-1.5,1.5)
x5 <- runif(5000,-1,1)
x6 <- runif(6000,-0.5,0.5)
x  <- c(x1,x2,x3,x4,x5,x6)
hist(x, prob=T, ylim=c(0,0.6), main=expression(paste("Distribución leptocúrtica ",italic(g[2]>0))), xlab ="", ylab="Frecuencia relativa", col="coral", axes=F)
axis(2)
curve(dnorm, from=-3.5, to=3.5, add=TRUE, col="royalblue", lwd=2)
dev.copy2eps(file="img/descriptiva/distribucion_leptocurtica.eps", width=5, height=5, pointsize=10)
dev.off()

xfig(file="img/descriptiva/distribucion_leptocurtica.fig", onefile=TRUE, width=5, height=5, pointsize=10)
hist(x, prob=T, ylim=c(0,0.6), main=expression(paste("Distribución leptocúrtica ",italic(g[2]>0))), xlab ="", ylab="Frecuencia relativa", col="coral", axes=F)
axis(2)
curve(dnorm, from=-3.5, to=3.5, add=TRUE, col="royalblue", lwd=2)
dev.off()


# Histograma simétrico transformacion variables
x11()
x <- rnorm(1000000)
par(mai=c(0,0,0,0))
hist(x, nclass=40, xlim=c(-3.5,3.5), ylim=c(0,0.4), prob=TRUE, main="", col="coral", axes=FALSE)
dev.copy2eps(file="img/descriptiva/histograma_simetrico.eps", width=5, height=5, pointsize=10)
dev.off()

xfig(file="img/descriptiva/histograma_simetrico.fig", onefile=TRUE, width=5, height=5, pointsize=10)
par(mai=c(0,0,0,0))
hist(x, nclass=40, xlim=c(-3.5,3.5), ylim=c(0,0.4), prob=TRUE, main="", col="coral", axes=FALSE)
dev.copy2eps(file="img/descriptiva/histograma_simetrico.eps", width=5, height=5, pointsize=10)
dev.off()
